Upgrade pywebpush to fix cryptography compatibility issue
The push notification test was failing with:
TypeError: curve must be an EllipticCurve instance

This is due to pywebpush 1.14.0 being incompatible with newer versions
of the cryptography library. Upgraded to pywebpush>=2.0.0 which has
fixed this compatibility issue.

The container needs to be rebuilt to pick up this dependency change.